name: Run App

on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  update-api-url:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve

    - name: Get API URL
      id: get_api_url
      run: echo "::set-output name=url::$(terraform output api_url)"

    - name: Modify index.html
      run: |
        sed -i "s/{{API_URL}}/${{ steps.get_api_url.outputs.url }}/g" ../my-webapp-repo/index.html

    - name: Commit changes
      run: |
        cd ../my-webapp-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "Update API URL"
        git push
